### ISSUE TITLE
Help Wanted: How to deploy the doc in local development , covert the asciidoc to html and visit like online?

### ISSUE THREAD

**Issue by awxiaoxian2020** [jcohy/jcohy-docs#31]
I want to know how to run this project in my local enviroment. And I fork this repo and then change a lot. I want to deploy the html to a website with [my own content](https://github.com/awxiaoxian2020/Spring-Chinese-Doc/blob/lee-doc/README.md). I need help, thank you.

**Comment by awxiaoxian2020** [comment]
I found that it has its own repo. thank you.

**Comment by jiachao23** [comment]
感谢您的关注，是的，他有自己的线上地址 https://www.jcohy.com
