### ISSUE TITLE
网站打不开

### ISSUE THREAD

**Issue by jujunchen** [jcohy/jcohy-docs#44]
docs.jcohy.com 地址打不开，www的也不行

**Comment by jiachao23** [comment]
可以的，欢迎欢迎。网站现在可以打开了。docs 那个是托管在阿里云上的，都是些静态页面，需指定路径。

**Comment by jiachao23** [comment]
@jujunchen 最近刚换了服务器提供商，域名还在备案接入中，待恢复后才可正常访问。可以暂时使用 124.222.90.247 公网 ip 访问
